name: 01 - Building Blocks

on: push

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: Type something
              run: echo "Hello world"
    second-job:
        runs-on: ubuntu-latest
        steps:
            - name: Step to Succeed
              run: |
                echo "This one will succeed"
                exit 0
            - name: Only Runs if Previous step succeeds
              run: echo "This should only RUN if previous steps succeed"
